name: CI - Fase 1 (Node + Terraform)

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # ... (node-ci igual ao seu)

  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt (write)
        run: terraform fmt -recursive

      - name: Commit Terraform fmt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(terraform): fmt"
          file_pattern: infra/terraform/*.tf

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          terraform plan \
            -var="aws_region=${AWS_REGION}" \
            -var="bucket_name=devops-fase1-rafael-2025-artifacts"
