name: IaC Apply (Terraform)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: AWS whoami (debug)
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
        run: |
          aws sts get-caller-identity
          echo "REGION=$AWS_REGION"

      - name: Terraform fmt & validate
        run: |
          terraform fmt -check -recursive
          terraform init -input=false
          terraform validate

      - name: Terraform plan
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
        run: |
          terraform plan -no-color -input=false \
            -var="aws_region=${AWS_REGION}" \
            -var="bucket_name=devops-fase1-rafael-2025-artifacts" \
            -var="create_ec2=false"

      - name: Terraform apply
        if: ${{ success() }}
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
        run: |
          terraform apply -auto-approve -no-color -input=false \
            -var="aws_region=${AWS_REGION}" \
            -var="bucket_name=devops-fase1-rafael-2025-artifacts" \
            -var="create_ec2=false"
